### ISSUE TITLE
dates close to 1950

### ISSUE THREAD

**Issue by timriffe** [josehcms/fertestr#13]
Hi @josehcms quick question(s), which might or might not be an issue:

The following works:
`fertestr::FetchLifeTableWpp2019("France", 1955, "female")`

But the following does not:
`fertestr::FetchLifeTableWpp2019("France", 1954, "female")`

- [ ] 1) Should we not in principle have data back to 1950 in `wpp2019`?
- [x] 2) Should we in any case do some cheap (hold constant) extrapolation to get back to 1950 if not?
- [x] 3) Should we detect if `year` is less than that available and give an _informative_ error?

* same story for fetching lifetales, etc

**Comment by josehcms** [comment]
Hey @timriffe! Thanks for your points. Indeed, I compute these life tables from mxM and mxF data from wpp2019 package which have data for 1950-1955, 1955-1960, 1960-1965,... 

I will work on this issue soon and use both approaches 2 and 3 you recommended. Instead of and informative error I think I will provide an informative warning and hold constant values back to 1950.

**Comment by josehcms** [comment]
@timriffe, I have just pushed a new version of fertestr that solved this issue. Thanks!
